version: "3.9"

services:
  server:
    build:
      context: .
      target: prod
    command: python3 server.py
  worker:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
