---

name: Staging CI/CD Pipeline

on: pull_request

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    with:
      debug: true
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}